### ISSUE TITLE
Large-Pack-1 Game Stats Error

### ISSUE THREAD

**Issue by GamingMineblox** [DogV2/OLD-RawPacks#1]
when i try to add the fortnite command to my discord bot it says that the code is invalid.
how can i fix that so i can have a fortnite stats command in my bot?

[Link To Commands](https://github.com/DogV2/DBM-Raw-Packs/tree/Large-Pack-1)

**Comment by OfficialGB** [comment]
i have the same problem

**Comment by GamingMineblox** [comment]
@officialGB
Is it only fortnite for you or more?
